[package]
name = "lushus-config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
handlebars = "4.3"
serde = { version = "1.0", features = ["derive"] }
serde_with = "2.2"
serde_yaml = "0.9"
thiserror = "1.0"
url = "2.2"
